import * as pgSchema from './schema.pg';
import * as sqliteSchema from './schema.sqlite';
import { DB_TYPE } from '../config/database';

export const customers = (DB_TYPE === 'postgres' ? pgSchema.customers : sqliteSchema.customers) as typeof sqliteSchema.customers;
export const ledgers = (DB_TYPE === 'postgres' ? pgSchema.ledgers : sqliteSchema.ledgers) as typeof sqliteSchema.ledgers;
export const suppliers = (DB_TYPE === 'postgres' ? pgSchema.suppliers : sqliteSchema.suppliers) as typeof sqliteSchema.suppliers;
export const supplier_ledgers = (DB_TYPE === 'postgres' ? pgSchema.supplier_ledgers : sqliteSchema.supplier_ledgers) as typeof sqliteSchema.supplier_ledgers;
export const products = (DB_TYPE === 'postgres' ? pgSchema.products : sqliteSchema.products) as typeof sqliteSchema.products;
export const settings = (DB_TYPE === 'postgres' ? pgSchema.settings : sqliteSchema.settings) as typeof sqliteSchema.settings;
export const logistics_vehicles = (DB_TYPE === 'postgres' ? pgSchema.logistics_vehicles : sqliteSchema.logistics_vehicles) as typeof sqliteSchema.logistics_vehicles;
export const logistics_employees = (DB_TYPE === 'postgres' ? pgSchema.logistics_employees : sqliteSchema.logistics_employees) as typeof sqliteSchema.logistics_employees;
export const logistics_expenses = (DB_TYPE === 'postgres' ? pgSchema.logistics_expenses : sqliteSchema.logistics_expenses) as typeof sqliteSchema.logistics_expenses;
export const logistics_bucket_rentals = (DB_TYPE === 'postgres' ? pgSchema.logistics_bucket_rentals : sqliteSchema.logistics_bucket_rentals) as typeof sqliteSchema.logistics_bucket_rentals;
export const misc_expenses = (DB_TYPE === 'postgres' ? pgSchema.misc_expenses : sqliteSchema.misc_expenses) as typeof sqliteSchema.misc_expenses;
export const invoices = (DB_TYPE === 'postgres' ? pgSchema.invoices : sqliteSchema.invoices) as typeof sqliteSchema.invoices;
export const invoice_items = (DB_TYPE === 'postgres' ? pgSchema.invoice_items : sqliteSchema.invoice_items) as typeof sqliteSchema.invoice_items;
export const diary = (DB_TYPE === 'postgres' ? pgSchema.diary : sqliteSchema.diary) as typeof sqliteSchema.diary;
export const diary_items = (DB_TYPE === 'postgres' ? pgSchema.diary_items : sqliteSchema.diary_items) as typeof sqliteSchema.diary_items;
export const diary_notes = (DB_TYPE === 'postgres' ? pgSchema.diary_notes : sqliteSchema.diary_notes) as typeof sqliteSchema.diary_notes;
export const sync_logs = (DB_TYPE === 'postgres' ? pgSchema.sync_logs : sqliteSchema.sync_logs) as typeof sqliteSchema.sync_logs;
